version: "3.8"
services:

#La configuration du proxy nginx.
#Les fichiers de conf ont été concus pour vous permettre d'injecter des variables lors du build du conteneur nginx.
    nginx-proxy:
        command: >
          /bin/sh -c "export HOST=nextcloud SERVER_LISTEN_PORT=8080 SERVER_NAME=drive.nassar.free.ci && 
            envsubst '$$HOST $$SERVER_LISTEN_PORT $$SERVER_NAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/nginx.conf &&
            exec nginx -g 'daemon off;'"
        container_name: nginx-proxy
        image: nginx:alpine
        restart: always
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/conf.d/default.template:/etc/nginx/conf.d/default.template
          - ${VOLUME_PATH:?err}/nextcloud:/var/www/html

#La configuration de l'application nextcloud. 
#Les credentials visibles sont utilisés par defaut si les variables n'ont pas été definies.
    app-nextcloud:
        image: nextcloud:20.0.10-fpm-alpine
        restart: always
        volumes:
            - ${VOLUME_PATH:?err}/nextcloud:/var/www/html
        environment:
            MYSQL_USER: ${MYSQL_USER:-dbuser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dr1v@@E}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-dbdrive}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dr1v@@E}

#La configuration de la base de donnée pour nextcloud. 
#Les credentials visibles sont utilisés par defaut si les variables n'ont pas été definies.
    mysql:
        command: [--ssl=0]
        environment:
            MYSQL_USER: ${MYSQL_USER:-dbuser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dr1v@@E}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-dbdrive}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dr1v@@E}
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-dr1vE}"]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s
        image: mysql:5.7
        restart: always
        volumes:
            - ${VOLUME_PATH:?err}/mysql:/var/lib/mysql

#La configuration de l'adminer pour la base de donnée mysql.
#Adminer est un outil qui vous permet de manipuler votre base de donnée via interface graphique
    adminer:
        container_name: adminer
        depends_on:
          - mysql
        image: adminer
        ports:
          - ${ADMINER_PUBLISHED_PORT:-8090}:8080
        restart: always
