version: "3.8"
services:
    nginx-proxy:
        command: >
          /bin/sh -c "export HOST=nextcloud SERVER_LISTEN_PORT=8080 SERVER_NAME=drive.nassar.free.ci && 
            envsubst '$$HOST $$SERVER_LISTEN_PORT $$SERVER_NAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/nginx.conf &&
            exec nginx -g 'daemon off;'"
        container_name: nginx-proxy
        image: nginx:alpine
        restart: always
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/conf.d/default.template:/etc/nginx/conf.d/default.template
          - ${VOLUME_PATH:?err}/nextcloud:/var/www/html

    app-nextcloud:
        container_name: app-nextcloud
        environment:
            MYSQL_USER: ${MYSQL_USER:-dbuser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dr1v@@E}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-dbdrive}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dr1v@@E}
        image: nextcloud:20.0.10-fpm-alpine
        restart: always
        volumes:
            - ${VOLUME_PATH:?err}/nextcloud:/var/www/html

    mysql:
        command: [--ssl=0]
        container_name: mysql
        environment:
            MYSQL_USER: ${MYSQL_USER:-dbuser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dr1v@@E}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-dbdrive}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dr1v@@E}
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-dr1vE}"]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s
        image: mysql:5.7
        restart: always
        volumes:
            - ${VOLUME_PATH:?err}/mysql:/var/lib/mysql

    adminer:
        container_name: adminer
        depends_on:
          - mysql
        image: adminer
        restart: always
