version: "3.8"
services:
    nginx-proxy:
        container_name: nginx-proxy
        depends_on:
          - app-nextcloud    
        environment:
          - app-nextcloud      
        image: nginx:alpine
        restart: always
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ${VOLUME_PATH:?err}/nextcloud:/var/www/html:ro

    app-nextcloud:
        container_name: app-nextcloud
        depends_on:
            - mariadb
            - redis
        environment:
            MARIADB_USER: ${MARIADB_USER:-dbuser}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-dr1v@@E}
            MARIADB_DATABASE: ${MARIADB_DATABASE:-dbdrive}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-dr1v@@E}
            REDIS_HOST: redis
        image: nextcloud:20.0.10-fpm-alpine
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.app-nextcloud.rule=Host(`drive.${DOMAIN:?err}`)"
          - "traefik.http.routers.app-nextcloud.entrypoints=https"
          - "traefik.http.routers.app-nextcloud.tls=true"
          - "traefik.http.routers.app-nextcloud.tls.certResolver=letsencrypt"
        restart: always
        volumes:
            - ${VOLUME_PATH:?err}/nextcloud:/var/www/html

    redis:
        container_name: redis
        image: redis:alpine
        restart: always 

    mariadb:
        command: [--ssl=0]
        container_name: mariadb
        environment:
            MARIADB_USER: ${MARIADB_USER:-dbuser}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-dr1v@@E}
            MARIADB_DATABASE: ${MARIADB_DATABASE:-dbdrive}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-dr1v@@E}
        image: mariadb:10.5.10
        restart: always
        volumes:
            - ${VOLUME_PATH:?err}/mariadb:/var/lib/mysql

    adminer:
        container_name: adminer
        depends_on:
          - mariadb
        image: adminer
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.adminer.rule=Host(`adminer.${DOMAIN:?err}`)"
          - "traefik.http.routers.adminer.entrypoints=https"
          - "traefik.http.routers.adminer.tls=true"
          - "traefik.http.routers.adminer.tls.certResolver=letsencrypt"
        restart: always
