version: "3.8"
services:
    nginx-proxy:
        container_name: nginx-proxy
        depends_on:
          - app-nextcloud        
        image: nginx:alpine
        restart: always
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ${VOLUME_PATH:?err}/nextcloud:/var/www/html

    app-nextcloud:
        container_name: app-nextcloud
        depends_on:
            - mysql
            - redis
        environment:
            MYSQL_USER: ${MYSQL_USER:-dbuser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dr1v@@E}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-dbdrive}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dr1v@@E}
            REDIS_HOST: redis
        image: nextcloud:20.0.10-fpm-alpine
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.app-nextcloud.rule=Host(`drive.${DOMAIN:?err}`)"
          - "traefik.http.routers.app-nextcloud.entrypoints=https"
          - "traefik.http.routers.app-nextcloud.tls=true"
          - "traefik.http.routers.app-nextcloud.tls.certResolver=letsencrypt"
        restart: always
        volumes:
            - ${VOLUME_PATH:?err}/nextcloud:/var/www/html

    redis:
        container_name: redis
        image: redis:alpine
        restart: always 

    mysql:
        command: [--ssl=0]
        container_name: mysql
        environment:
            MYSQL_USER: ${MYSQL_USER:-dbuser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dr1v@@E}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-dbdrive}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dr1v@@E}
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-dr1vE}"]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s
        image: mysql:5.7
        restart: always
        volumes:
            - ${VOLUME_PATH:?err}/mysql:/var/lib/mysql

    adminer:
        container_name: adminer
        depends_on:
          - mysql
        image: adminer
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.adminer.rule=Host(`adminer.${DOMAIN:?err}`)"
          - "traefik.http.routers.adminer.entrypoints=https"
          - "traefik.http.routers.adminer.tls=true"
          - "traefik.http.routers.adminer.tls.certResolver=letsencrypt"
        restart: always
